version: "3.7"
services:
  osparc-python-runner-tensorflow:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
      target: production
